# - Try to find the Libevent config processing library
# Once done this will define
#
# LIBEVENT_FOUND - System has Libevent
# LIBEVENT_INCLUDE_DIR - the Libevent include directory
# LIBEVENT_LIBRARIES 0 The libraries needed to use Libevent

FIND_PATH(LIBEVENT_INCLUDE_DIR NAMES event.h)
FIND_LIBRARY(LIBEVENT_LIBRARY NAMES event)
FIND_LIBRARY(LIBEVENT_CORE_LIBRARY NAMES event_core)
FIND_LIBRARY(LIBEVENT_PTHREADS_LIBRARY NAMES event_pthreads)
FIND_LIBRARY(LIBEVENT_EXTRA_LIBRARY NAMES event_extra)
FIND_LIBRARY(LIBEVENT_OPENSSL_LIBRARY NAMES event_openssl)

MARK_AS_ADVANCED(
    LIBEVENT_INCLUDE_DIR
    LIBEVENT_LIBRARY
    LIBEVENT_PTHREADS_LIBRARY
    LIBEVENT_OPENSSL_LIBRARY
    LIBEVENT_CORE_LIBRARY
    LIBEVENT_EXTRA_LIBRARY
    )
